title: "Документы"
description: "documents related to early Chabad history"
url: "www.alter-rebbe.org"
author: "Leonid Dubinsky"
email: dub@opentorah.org
timezone: "America/New_York"
google-analytics: "UA-154490117-1"

social:
  github:  opentorah
  twitter: theopentorah
