title: "Документы"
# TODO title: Архив 19 кислева
description: "documents related to early Chabad history"
url: "ng.alter-rebbe.org"
author: "Leonid Dubinsky"
email: dub@opentorah.org
timezone: "America/New_York"
lang: ru
google-analytics: "UA-154490117-1"
favicon: alter-rebbe.jpg
facsimiles-url: https://storage.googleapis.com/facsimiles.alter-rebbe.org/
tei-default-calendar: julian
named-windows: true

home: /archive-index.html

header-pages:
  - names.xml
  - archive-collections
  - /note/help.md
  - /note/about.md
  - posts

social:
  github:  opentorah
  twitter: theopentorah
