plugins {
  id 'idea'
  id 'scala'
  id 'org.podval.conventions'
  id 'org.podval.tools.site-publisher' version '0.2.0'
}

description = '19 Kislev Archive'

idea {
  module {
    excludeDirs += [
      file('.idea'),
      file('gradle')
    ]
  }
}

// There is no Java in the project :)
project.gradle.startParameter.excludedTaskNames.add('compileJava')

site {
  treatErrorsAsWarnings = true
}
